plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.teplayakompaniya.tk4'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.teplayakompaniya.tk4'
        minSdk 26
        targetSdk 35
        versionCode 400001
        versionName '4.0.0-alpha1'
    }
}

dependencies {
}
